# NumPy beginner exercise solutions

Compare the *idea* of your solution, not only the exact spelling. NumPy often offers more than
one correct approach.


In [1]:
import numpy as np


## Solution 1


In [2]:
exercise_1 = np.arange(1, 11)
print(exercise_1)
print(exercise_1.shape, exercise_1.size, exercise_1.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
(10,) 10 int64


## Solution 2


In [3]:
exercise_2 = np.arange(1, 13).reshape(3, 4)
print(exercise_2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Solution 3


In [4]:
matrix = np.arange(1, 17).reshape(4, 4)
exercise_3 = matrix[1:3, 0:2]
print(exercise_3)


[[ 5  6]
 [ 9 10]]


## Solution 4


In [5]:
scores = np.array([9, 15, 20, 12, 18])
exercise_4 = scores[scores >= 15]
print(exercise_4)


[15 20 18]


## Solution 5


In [6]:
data = np.array([[1, 2, 3], [4, 5, 6]])
exercise_5 = data + np.array([100, 200, 300])
print(exercise_5)


[[101 202 303]
 [104 205 306]]


## Solution 6


In [7]:
data = np.array([[1, 2, 3], [4, 5, 6]])
column_sums = data.sum(axis=0)
row_means = data.mean(axis=1)
print(column_sums)
print(row_means)


[5 7 9]
[2. 5.]


## Solution 7


In [8]:
features = np.array([[1.0, 10.0], [2.0, 20.0], [3.0, 30.0]])
standardized = (features - features.mean(axis=0)) / features.std(axis=0)
print(standardized)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


## Solution 8


In [9]:
rng = np.random.default_rng(42)
exercise_8 = rng.integers(0, 10, size=(2, 5))
print(exercise_8)


[[0 7 6 4 4]
 [8 0 6 2 0]]


## Solution 9


In [10]:
features = np.array([[1.0, 2.0], [3.0, 4.0]])
weights = np.array([0.5, 2.0])
predictions = features @ weights
print(predictions)


[4.5 9.5]


## Solution 10


In [11]:
padded_ids = np.array([[2, 5, 7, 0], [4, 3, 0, 0]])
mask = (padded_ids != 0).astype(np.int32)
print(mask)


[[1 1 1 0]
 [1 1 0 0]]


## Challenge solution


In [12]:
def cosine_similarity(x, y):
    denominator = np.linalg.norm(x) * np.linalg.norm(y)
    if denominator == 0:
        return 0.0
    return float(np.dot(x, y) / denominator)

print(cosine_similarity(np.array([1.0, 0.0]), np.array([1.0, 1.0])))


0.7071067811865475
