# 1. Arrays, creation, and properties

## Toy idea: an array is a tray with a shape

A one-dimensional array is like one row of boxes. A two-dimensional array is like a table.
A three-dimensional array is like a stack of tables.

**Learning goals**

- create 1D, 2D, and 3D arrays;
- read `ndim`, `shape`, `size`, and `dtype`;
- use `zeros`, `ones`, `full`, `arange`, and `linspace`;
- convert data types safely;
- understand why rectangular shape matters.


In [1]:
import numpy as np


## Create an array from a Python list


In [2]:
a = np.array([1, 2, 3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


## Four useful questions about every array

- `ndim`: How many axes does it have?
- `shape`: How long is each axis?
- `size`: How many values are there in total?
- `dtype`: What type of value is stored?


In [3]:
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)


ndim: 1
shape: (3,)
size: 3
dtype: int64


A 1D array with three values has shape `(3,)`, not `(1, 3)`. The comma tells Python that
this is a one-item tuple describing one axis.


In [4]:
houses = np.array([
    [75, 2, 15],
    [120, 3, 7],
    [55, 1, 30],
])

print(houses)
print("shape:", houses.shape)
print("ndim:", houses.ndim)
print("size:", houses.size)


[[ 75   2  15]
 [120   3   7]
 [ 55   1  30]]
shape: (3, 3)
ndim: 2
size: 9


Here, each row can represent one house and the columns can represent area, number of rooms,
and age. The shape `(3, 3)` means 3 rows and 3 columns.


In [5]:
tiny_image_batch = np.array([
    [[0, 255], [255, 0]],
    [[255, 255], [0, 0]],
])

print(tiny_image_batch)
print("shape:", tiny_image_batch.shape)
print("ndim:", tiny_image_batch.ndim)


[[[  0 255]
  [255   0]]

 [[255 255]
  [  0   0]]]
shape: (2, 2, 2)
ndim: 3


## Common array constructors


In [6]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3), dtype=np.int32)
eights = np.full((2, 3), 8)

print("zeros:\n", zeros)
print("ones:\n", ones)
print("full:\n", eights)


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1 1 1]
 [1 1 1]]
full:
 [[8 8 8]
 [8 8 8]]


## `arange` versus `linspace`

- `arange(start, stop, step)` controls the step and excludes `stop`.
- `linspace(start, stop, count)` controls the number of evenly spaced values and normally
  includes both endpoints.


In [7]:
even_numbers = np.arange(0, 10, 2)
five_points = np.linspace(0, 1, 5)

print(even_numbers)
print(five_points)


[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Data types

NumPy usually chooses a type automatically. You can request a type or convert later.
A conversion may lose information—for example, converting `3.9` to an integer removes the
decimal part rather than rounding it.


In [8]:
integers = np.array([1, 2, 3], dtype=np.int32)
floats = integers.astype(np.float32)
truncated = np.array([1.2, 3.9]).astype(np.int32)

print(integers, integers.dtype)
print(floats, floats.dtype)
print(truncated, truncated.dtype)


[1 2 3] int32
[1. 2. 3.] float32
[1 3] int32


## Helpful inspection


In [9]:
print("item size in bytes:", integers.itemsize)
print("total data bytes:", integers.nbytes)
print("calculation check:", integers.size * integers.itemsize)


item size in bytes: 4
total data bytes: 12
calculation check: 12


## Rectangular arrays

A normal numerical NumPy array must be rectangular. Rows with different lengths do not form
a clean numeric matrix. Padding variable-length sequences will be discussed in the NLP lesson.


In [10]:
rectangular = np.array([[1, 2], [3, 4]])
print(rectangular)
print(rectangular.shape)


[[1 2]
 [3 4]]
(2, 2)


## Tiny checkpoint

Create a 3 × 4 array filled with the value 7, then print its shape and size.


In [11]:
checkpoint = np.full((3, 4), 7)
print(checkpoint)
print("shape:", checkpoint.shape)
print("size:", checkpoint.size)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
shape: (3, 4)
size: 12
