# 2. Indexing, slicing, views, copies, and masks

## Toy idea: indexing chooses one box; slicing chooses a window

**Learning goals**

- select values from 1D, 2D, and 3D arrays;
- slice rows and columns;
- understand the important view-versus-copy rule;
- filter data with Boolean masks;
- select several positions with integer arrays.


In [1]:
import numpy as np


## 1D indexing

Python starts counting at zero. Negative indices count from the end.


In [2]:
values = np.array([10, 20, 30, 40, 50])

print("first:", values[0])
print("third:", values[2])
print("last:", values[-1])


first: 10
third: 30
last: 50


## 1D slicing

The pattern is `start:stop:step`. The `stop` position is excluded.


In [3]:
print(values[1:4])
print(values[:3])
print(values[::2])
print(values[::-1])


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


## 2D indexing

Use `array[row, column]`. This is usually clearer than `array[row][column]`.


In [4]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

print("row 0:", matrix[0])
print("value at row 1, column 2:", matrix[1, 2])
print("last row, last column:", matrix[-1, -1])


row 0: [1 2 3 4]
value at row 1, column 2: 7
last row, last column: 12


## Select rows and columns


In [5]:
print("first two rows:\n", matrix[:2, :])
print("middle columns:\n", matrix[:, 1:3])
print("small block:\n", matrix[1:, 2:])


first two rows:
 [[1 2 3 4]
 [5 6 7 8]]
middle columns:
 [[ 2  3]
 [ 6  7]
 [10 11]]
small block:
 [[ 7  8]
 [11 12]]


## 3D indexing

For a 3D array, think `array[layer, row, column]`.


In [6]:
cube = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
])

print("shape:", cube.shape)
print("one value:", cube[0, 0, 1])
print("one row from layer 1:", cube[1, 0])


shape: (2, 3, 2)
one value: 2
one row from layer 1: [7 8]


## Very important: many slices are views

A **view** is like a window looking at the original array. Changing the view can change the
original array too.


In [7]:
original = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

view = original[:, :2]
view[0, 0] = 999

print("view:\n", view)
print("original changed too:\n", original)


view:
 [[999   2]
 [  4   5]]
original changed too:
 [[999   2   3]
 [  4   5   6]]


## Use `.copy()` when you need an independent array


In [8]:
original = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

independent = original[:, :2].copy()
independent[0, 0] = 999

print("copy:\n", independent)
print("original stays unchanged:\n", original)


copy:
 [[999   2]
 [  4   5]]
original stays unchanged:
 [[1 2 3]
 [4 5 6]]


## Boolean masks

A comparison creates an array of `True` and `False`. The mask can then select matching values.


In [9]:
scores = np.array([12, 18, 9, 20, 15])
passed_mask = scores >= 15

print("mask:", passed_mask)
print("passed scores:", scores[passed_mask])


mask: [False  True False  True  True]
passed scores: [18 20 15]


In [10]:
between_10_and_18 = (scores >= 10) & (scores <= 18)
print(scores[between_10_and_18])


[12 18 15]


Use `&`, `|`, and `~` for element-wise logical AND, OR, and NOT. Put each comparison inside
parentheses.


## Replace values using a mask


In [11]:
clipped_scores = scores.copy()
clipped_scores[clipped_scores < 10] = 10
print(clipped_scores)


[12 18 10 20 15]


## Fancy indexing

An integer array can choose several positions in a custom order.


In [12]:
words = np.array(["کتاب", "مدرسه", "زبان", "رایانه"])
chosen_positions = np.array([3, 0, 3])
print(words[chosen_positions])


['رایانه' 'کتاب' 'رایانه']


## Tiny checkpoint

Select the second and fourth columns from the matrix below.


In [13]:
checkpoint_matrix = np.arange(1, 13).reshape(3, 4)
selected = checkpoint_matrix[:, [1, 3]]

print(checkpoint_matrix)
print("selected:\n", selected)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
selected:
 [[ 2  4]
 [ 6  8]
 [10 12]]
