# 3. Shape transformations and combining arrays

## Toy idea: reshaping rearranges the same blocks into a new tray

Reshaping does not invent or delete values. The number of slots before and after must match.

**Learning goals**

- use `reshape` correctly;
- let NumPy infer one dimension with `-1`;
- flatten arrays;
- transpose axes;
- add and remove length-one dimensions;
- concatenate and stack arrays.


In [1]:
import numpy as np


## Reshape


In [2]:
values = np.arange(1, 13)
matrix = values.reshape(3, 4)

print(values)
print(matrix)
print("same size:", values.size == matrix.size)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
same size: True


Twelve values can become `3 × 4`, `4 × 3`, `2 × 6`, or other shapes whose dimensions
multiply to 12. They cannot become `4 × 4`, because that would need 16 values.


In [3]:
try:
    impossible = values.reshape(4, 4)
except ValueError as error:
    print("Reshape error:", error)


Reshape error: cannot reshape array of size 12 into shape (4,4)


## Let NumPy calculate one dimension


In [4]:
inferred = values.reshape(3, -1)
print(inferred)
print(inferred.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


Only one dimension may be `-1`, because NumPy needs enough information to calculate it.


## Flattening

- `ravel()` often returns a view when possible.
- `flatten()` always returns a copy.


In [5]:
matrix = np.arange(1, 7).reshape(2, 3)
raveled = matrix.ravel()
flattened = matrix.flatten()

print("matrix:\n", matrix)
print("ravel:", raveled)
print("flatten:", flattened)


matrix:
 [[1 2 3]
 [4 5 6]]
ravel: [1 2 3 4 5 6]
flatten: [1 2 3 4 5 6]


## Transpose

For a 2D matrix, `.T` swaps rows and columns.


In [6]:
print("original shape:", matrix.shape)
print(matrix)
print("transposed shape:", matrix.T.shape)
print(matrix.T)


original shape: (2, 3)
[[1 2 3]
 [4 5 6]]
transposed shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## Add a new axis

A single feature vector with shape `(3,)` can become one row `(1, 3)` or one column `(3, 1)`.
This is useful when machine-learning code expects a batch dimension.


In [7]:
vector = np.array([10, 20, 30])
row_vector = vector[np.newaxis, :]
column_vector = vector[:, np.newaxis]

print("vector:", vector.shape)
print("row:", row_vector.shape)
print("column:", column_vector.shape)


vector: (3,)
row: (1, 3)
column: (3, 1)


`np.expand_dims(vector, axis=0)` is another clear way to add an axis. `np.squeeze()` removes
axes whose length is 1.


In [8]:
expanded = np.expand_dims(vector, axis=0)
squeezed = np.squeeze(expanded)

print(expanded.shape)
print(squeezed.shape)


(1, 3)
(3,)


## Concatenate: join along an existing axis


In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

joined_rows = np.concatenate([a, b], axis=0)
print(joined_rows)


[[1 2]
 [3 4]
 [5 6]]


In [10]:
c = np.array([[10], [20]])
joined_columns = np.concatenate([a, c], axis=1)
print(joined_columns)


[[ 1  2 10]
 [ 3  4 20]]


## Stack: create a new axis


In [11]:
first = np.array([1, 2, 3])
second = np.array([4, 5, 6])

rows = np.stack([first, second], axis=0)
columns = np.stack([first, second], axis=1)

print("row stack:\n", rows)
print("column stack:\n", columns)


row stack:
 [[1 2 3]
 [4 5 6]]
column stack:
 [[1 4]
 [2 5]
 [3 6]]


## Tiny checkpoint

Turn the sequence `0..19` into a matrix with 5 rows. Let NumPy infer the number of columns.


In [12]:
checkpoint = np.arange(20).reshape(5, -1)
print(checkpoint)
print(checkpoint.shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
