# 4. Vectorization and broadcasting

## Toy idea: give one instruction to a whole classroom

Vectorization means applying operations to arrays instead of writing a Python loop for every
element. Broadcasting lets differently shaped arrays work together when their dimensions are
compatible.

**Learning goals**

- perform element-wise arithmetic;
- distinguish element-wise multiplication from matrix multiplication;
- understand basic broadcasting rules;
- use universal functions such as `sqrt`, `exp`, and `log`;
- write clearer numerical code without unnecessary loops.


In [1]:
import numpy as np


## Element-wise operations


In [2]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("add:", a + b)
print("subtract:", b - a)
print("multiply:", a * b)
print("divide:", b / a)
print("power:", a ** 2)


add: [11 22 33]
subtract: [ 9 18 27]
multiply: [10 40 90]
divide: [10. 10. 10.]
power: [1 4 9]


## Scalar broadcasting

A scalar behaves as if it were copied to every position.


In [3]:
scores = np.array([12, 15, 18])
print(scores + 2)
print(scores / 20)


[14 17 20]
[0.6  0.75 0.9 ]


## Broadcasting a row across a matrix


In [4]:
data = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
])
offsets = np.array([1, 2, 3])

print(data + offsets)


[[  11  102 1003]
 [  21  202 2003]]


Shapes are compared from right to left. Two dimensions are compatible when they are equal or
one of them is 1.

Here `(2, 3)` and `(3,)` are compatible because the last dimensions are both 3. NumPy treats
`(3,)` like `(1, 3)` and repeats it across the two rows.


## Broadcasting a column


In [5]:
row_offsets = np.array([[100], [200]])
print(data + row_offsets)


[[ 110  200 1100]
 [ 220  400 2200]]


## A common machine-learning pattern: standardization

Subtract each feature's mean and divide by its standard deviation. The mean and standard
deviation have shape `(number_of_features,)`, so they broadcast across all rows.


In [6]:
features = np.array([
    [1.0, 10.0],
    [2.0, 20.0],
    [3.0, 30.0],
])

means = features.mean(axis=0)
standard_deviations = features.std(axis=0)
standardized = (features - means) / standard_deviations

print("means:", means)
print("standard deviations:", standard_deviations)
print("standardized:\n", standardized)


means: [ 2. 20.]
standard deviations: [0.81649658 8.16496581]
standardized:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


## Universal functions (ufuncs)

NumPy functions operate element by element and return arrays.


In [7]:
values = np.array([1.0, 4.0, 9.0])
print("sqrt:", np.sqrt(values))
print("exp:", np.exp(np.array([0.0, 1.0])))
print("log:", np.log(np.array([1.0, np.e])))


sqrt: [1. 2. 3.]
exp: [1.         2.71828183]
log: [0. 1.]


## Conditional selection with `np.where`


In [8]:
scores = np.array([8, 14, 17, 9, 20])
labels = np.where(scores >= 10, "pass", "fail")
print(labels)


['fail' 'pass' 'pass' 'fail' 'pass']


## Element-wise multiplication is not matrix multiplication


In [9]:
left = np.array([[1, 2], [3, 4]])
right = np.array([[5, 6], [7, 8]])

print("element-wise:\n", left * right)
print("matrix multiplication:\n", left @ right)


element-wise:
 [[ 5 12]
 [21 32]]
matrix multiplication:
 [[19 22]
 [43 50]]


## A broadcasting error can teach us about shapes


In [10]:
try:
    bad = np.ones((2, 3)) + np.ones((2,))
except ValueError as error:
    print("Broadcasting error:", error)


Broadcasting error: operands could not be broadcast together with shapes (2,3) (2,) 


## Tiny checkpoint

Add the vector `[10, 20, 30]` to every row of a 2 × 3 matrix.


In [11]:
checkpoint_matrix = np.array([[1, 2, 3], [4, 5, 6]])
checkpoint_vector = np.array([10, 20, 30])
print(checkpoint_matrix + checkpoint_vector)


[[11 22 33]
 [14 25 36]]
