# 5. Aggregations, axes, and statistics

## Toy idea: an aggregation turns many values into a summary

Examples are sum, mean, minimum, maximum, variance, and standard deviation.

**Learning goals**

- compute common summary statistics;
- understand `axis=0` and `axis=1`;
- find positions with `argmin` and `argmax`;
- preserve dimensions with `keepdims=True`;
- handle missing numerical values represented by `NaN`.


In [1]:
import numpy as np


In [2]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(data)
print("shape:", data.shape)


[[1 2 3]
 [4 5 6]]
shape: (2, 3)


## Summary over the whole array


In [3]:
print("sum:", np.sum(data))
print("mean:", np.mean(data))
print("min:", np.min(data))
print("max:", np.max(data))
print("product:", np.prod(data))


sum: 21
mean: 3.5
min: 1
max: 6
product: 720


## Understanding axes

A reliable mental model is: **the selected axis disappears after aggregation**.

- `axis=0` removes the row axis, so values are combined down the rows and one result remains
  for each column.
- `axis=1` removes the column axis, so values are combined across each row.


In [4]:
print("sum, axis=0:", data.sum(axis=0))
print("sum, axis=1:", data.sum(axis=1))


sum, axis=0: [5 7 9]
sum, axis=1: [ 6 15]


In [5]:
print("mean of each column:", data.mean(axis=0))
print("mean of each row:", data.mean(axis=1))


mean of each column: [2.5 3.5 4.5]
mean of each row: [2. 5.]


## `keepdims=True`

Keeping a length-one axis can make later broadcasting easier.


In [6]:
row_means = data.mean(axis=1, keepdims=True)
centered_rows = data - row_means

print("row means shape:", row_means.shape)
print("row means:\n", row_means)
print("centered rows:\n", centered_rows)


row means shape: (2, 1)
row means:
 [[2.]
 [5.]]
centered rows:
 [[-1.  0.  1.]
 [-1.  0.  1.]]


## Variance and standard deviation

Variance measures average squared distance from the mean. Standard deviation is the square
root of variance and therefore uses the original unit.


In [7]:
values = np.array([1, 2, 3])
print("variance:", np.var(values))
print("standard deviation:", np.std(values))


variance: 0.6666666666666666
standard deviation: 0.816496580927726


NumPy uses population variance by default (`ddof=0`). For a sample estimate, use `ddof=1`.


In [8]:
print("population variance:", np.var(values, ddof=0))
print("sample variance:", np.var(values, ddof=1))


population variance: 0.6666666666666666
sample variance: 1.0


## Positions of minimum and maximum


In [9]:
scores = np.array([12, 19, 7, 18])
print("position of minimum:", np.argmin(scores))
print("position of maximum:", np.argmax(scores))


position of minimum: 2
position of maximum: 1


## Percentiles


In [10]:
ages = np.array([18, 20, 21, 25, 30, 45])
print("median:", np.median(ages))
print("25th, 50th, 75th percentiles:", np.percentile(ages, [25, 50, 75]))


median: 23.0
25th, 50th, 75th percentiles: [20.25 23.   28.75]


## Missing values with `NaN`

`NaN` means "not a number" and is commonly used for missing floating-point values.
Normal aggregations propagate it. The `nan...` versions ignore it.


In [11]:
measurements = np.array([10.0, np.nan, 14.0, 16.0])

print("ordinary mean:", np.mean(measurements))
print("NaN-aware mean:", np.nanmean(measurements))
print("missing mask:", np.isnan(measurements))


ordinary mean: nan
NaN-aware mean: 13.333333333333334
missing mask: [False  True False False]


## Tiny checkpoint

Calculate the maximum of each column and the mean of each row.


In [12]:
checkpoint = np.array([[3, 8, 2], [5, 1, 9]])
print("column maxima:", checkpoint.max(axis=0))
print("row means:", checkpoint.mean(axis=1))


column maxima: [5 8 9]
row means: [4.33333333 5.        ]
