# 6. Random numbers and reproducibility

## Toy idea: a seed is the starting page of a pretend-random story

Computers create pseudo-random numbers. Using the same seed starts the generator from the
same state, which helps us reproduce experiments.

**Learning goals**

- use NumPy's modern `Generator` API;
- generate integers and floating-point values;
- sample from common distributions;
- shuffle and choose items;
- split indices reproducibly.


In [1]:
import numpy as np


## Create a generator


In [2]:
rng = np.random.default_rng(seed=42)
print(rng)


Generator(PCG64)


## Random integers

The upper bound is excluded, like Python's `range`.


In [3]:
dice_rolls = rng.integers(low=1, high=7, size=10)
print(dice_rolls)


[1 5 4 3 3 6 1 5 2 1]


## Uniform random values between 0 and 1


In [4]:
uniform_values = rng.random(size=(2, 3))
print(uniform_values)


[[0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802]]


## Normal distribution


In [5]:
normal_values = rng.normal(loc=0.0, scale=1.0, size=8)
print(normal_values)
print("approximately centered near:", normal_values.mean())


[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078
 -0.9588826   0.8784503 ]
approximately centered near: 0.23344990048597214


## Choice


In [6]:
labels = np.array(["positive", "neutral", "negative"])
sampled_labels = rng.choice(labels, size=6, replace=True)
print(sampled_labels)


['positive' 'neutral' 'positive' 'negative' 'negative' 'neutral']


Sampling without replacement chooses distinct items.


In [7]:
sample_without_replacement = rng.choice(np.arange(10), size=4, replace=False)
print(sample_without_replacement)


[0 7 8 4]


## Shuffle and permutation

- `shuffle` changes an array in place.
- `permutation` returns a shuffled copy.


In [8]:
original = np.arange(8)
shuffled_copy = rng.permutation(original)

print("original:", original)
print("permuted copy:", shuffled_copy)


original: [0 1 2 3 4 5 6 7]
permuted copy: [6 3 7 2 0 5 1 4]


In [9]:
in_place = np.arange(8)
rng.shuffle(in_place)
print(in_place)


[0 6 4 5 1 2 7 3]


## Reproducibility

Two generators created with the same seed produce the same sequence.


In [10]:
first_rng = np.random.default_rng(123)
second_rng = np.random.default_rng(123)

first_draw = first_rng.integers(0, 100, size=5)
second_draw = second_rng.integers(0, 100, size=5)

print(first_draw)
print(second_draw)
print("equal:", np.array_equal(first_draw, second_draw))


[ 1 68 59  5 90]
[ 1 68 59  5 90]
equal: True


## Reproducible train/validation index split


In [11]:
number_of_examples = 10
indices = rng.permutation(number_of_examples)
split_point = 8

train_indices = indices[:split_point]
validation_indices = indices[split_point:]

print("train:", train_indices)
print("validation:", validation_indices)


train: [3 7 4 9 1 8 6 2]
validation: [0 5]


In real machine-learning projects, scikit-learn offers convenient splitting tools. This
example shows the underlying NumPy idea.


## Tiny checkpoint

Generate a reproducible 3 × 4 matrix of integers from 0 through 9.


In [12]:
checkpoint_rng = np.random.default_rng(7)
checkpoint = checkpoint_rng.integers(0, 10, size=(3, 4))
print(checkpoint)


[[9 6 6 8]
 [5 7 8 2]
 [0 3 2 8]]
