# NumPy beginner exercises

Work through these exercises **before** opening the solutions notebook. Replace each `None`
with your own code. The cells are written so the notebook still runs before completion.


In [1]:
import numpy as np


## Exercise 1 — Create and inspect

Create an array containing the integers 1 through 10. Print its shape, size, and dtype.


In [2]:
exercise_1 = None
print(exercise_1)


None


## Exercise 2 — Reshape

Create the integers 1 through 12 and reshape them to 3 rows and 4 columns.


In [3]:
exercise_2 = None
print(exercise_2)


None


## Exercise 3 — Slice

From the matrix below, select rows 1 and 2 and columns 0 and 1.


In [4]:
matrix = np.arange(1, 17).reshape(4, 4)
exercise_3 = None
print(matrix)
print(exercise_3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
None


## Exercise 4 — Boolean mask

Select all scores that are at least 15.


In [5]:
scores = np.array([9, 15, 20, 12, 18])
exercise_4 = None
print(exercise_4)


None


## Exercise 5 — Broadcasting

Add `[100, 200, 300]` to every row of the matrix.


In [6]:
data = np.array([[1, 2, 3], [4, 5, 6]])
exercise_5 = None
print(exercise_5)


None


## Exercise 6 — Axes

Calculate the sum of each column and the mean of each row.


In [7]:
data = np.array([[1, 2, 3], [4, 5, 6]])
column_sums = None
row_means = None
print(column_sums)
print(row_means)


None
None


## Exercise 7 — Standardize columns

Subtract each column mean and divide by each column standard deviation.


In [8]:
features = np.array([[1.0, 10.0], [2.0, 20.0], [3.0, 30.0]])
standardized = None
print(standardized)


None


## Exercise 8 — Reproducible randomness

With seed 42, create a 2 × 5 matrix of random integers from 0 through 9.


In [9]:
exercise_8 = None
print(exercise_8)


None


## Exercise 9 — Matrix-vector multiplication

Multiply the feature matrix by the weights to produce one prediction per row.


In [10]:
features = np.array([[1.0, 2.0], [3.0, 4.0]])
weights = np.array([0.5, 2.0])
predictions = None
print(predictions)


None


## Exercise 10 — NLP mask

Create a mask containing 1 for nonzero token IDs and 0 for padding IDs.


In [11]:
padded_ids = np.array([[2, 5, 7, 0], [4, 3, 0, 0]])
mask = None
print(mask)


None


## Challenge — Cosine similarity

Write a function that returns cosine similarity between two vectors. Return `0.0` if either
vector has zero length.


In [12]:
def cosine_similarity(x, y):
    # Replace this line with your solution.
    return None

print(cosine_similarity(np.array([1.0, 0.0]), np.array([1.0, 1.0])))


None
